apiVersion: v1
kind: Service

metadata:
  name: golang-app-svc
  labels:
    app: golang-app

spec:
  ports:
  - port: 3000
    nodePort: 30081

  selector:
    app: golang-app

  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: golang-app-deploy
  labels:
    app: golang-app

spec:
  replicas: 3

  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
      - name: golang-app-po
        image: lqshow/golang-app:0.0.1
        ports:
          - containerPort: 3000