apiVersion: v1
kind: Service
metadata:
  name: backend-svc-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: web-port
  selector:
    app: backend-svc-1

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-svc-1-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-svc-1
    spec:
      containers:
      - name: backend-svc-1-container
        image: lqshow/web-server:0.0.1
        ports:
        - containerPort: 3000
          name: web-port
          protocol: TCP
        env:
          - name: PORT
            value: "3000"