apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: add-configmap-to-volume-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: add-configmap-to-volume-pod
    spec:
      containers:
        - name: add-configmap-to-volume-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: game-config
            items:
            - key: game.properties
              path: game
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: default
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice