apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: using-all-key-value-pairs-in-configmap-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: using-all-key-value-pairs-in-configmap-pod
    spec:
      containers:
        - name: using-all-key-value-pairs-in-configmap-container
          image: lqshow/k8s-multi-container-pod:0.0.1
          envFrom:
          - configMapRef:
              name: default-config
          - configMapRef:
              name: production-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-config
  namespace: default
data:
  redis.host: localhost
  redis.port: "6379"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: production-config
  namespace: default
data:
  log.level: INFO
  redis.port: "8888"