apiVersion: v1
kind: Pod
metadata:
  name: consume-secret-in-volume-pod
  namespace: default
spec:
  containers:
  - name: consume-secret-in-volume-container
    image: redis
    volumeMounts:
    - name: foobar
      mountPath: /etc/foobar
      readOnly: true
  volumes:
  - name: foobar
    secret:
      secretName: consume-secret-in-volume-secret
---      

apiVersion: v1
kind: Secret
metadata:
  name: consume-secret-in-volume-secret
  namespace: default
type: Opaque
data:
  username: TFEK
  password: MTIzNDU2Cg==