apiVersion: v1
kind: Pod
metadata:
  name: consume-secret-env-pod
spec:
  containers:
  - name: consume-secret-env-container
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: consume-secret-env-secret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: consume-secret-env-secret
            key: password
  restartPolicy: Never
---      

apiVersion: v1
kind: Secret
metadata:
  name: consume-secret-env-secret
  namespace: default
type: Opaque
data:
  username: TFEK
  password: MTIzNDU2Cg==