apiVersion: v1
kind: Service

metadata:
  name: webapp-svc
  labels:
    app: webapp

spec:
  ports:
  - port: 80
    nodePort: 30080

  selector:
    app: webapp

  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: webapp-deploy
  labels:
    app: webapp

spec:
  replicas: 2         # 让 Deployment 创建2个 Pod 的副本
  
  template:           # Pod 模板
    metadata:
      labels:
        app: webapp   # 为所有 Pod 都打上这个标签，标签的 Key 是 app，value 是 webapp
    spec:
      containers:
      - name: webapp
        image: katacoda/docker-http-server:latest
        ports:
        - containerPort: 80