kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""] # 空字符串表明使用核心 API 组
  resources: ["pods"]
  verbs: ["get", "watch", "list"]