apiVersion: v1
kind: Pod

metadata:
  name: resource-pod
  
spec:
  containers:
  - name: resource-pod-container
    image: nginx
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
