apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  labels:
    app: nginx

spec:
  ports:
  - port: 3000
    name: http
    targetPort: 80
    protocol: TCP

  selector:
    app: nginx

  type: NodePort